const DB_NAME='ninnin-tcg',DB_VERSION=1;let db,currentModal=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>'₩'+Number(n||0).toLocaleString('ko-KR');
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;['cards','transactions','grading'].forEach(x=>{if(!d.objectStoreNames.contains(x))d.createObjectStore(x,{keyPath:'id'})})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
function all(name){return new Promise((res,rej)=>{const r=store(name).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(name,val){return new Promise((res,rej)=>{const r=store(name,'readwrite').put(val);r.onsuccess=()=>res(val);r.onerror=()=>rej(r.error)})}
function del(name,id){return new Promise((res,rej)=>{const r=store(name,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function clear(name){return new Promise((res,rej)=>{const r=store(name,'readwrite').clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
const titles={dashboard:['Dashboard','포켓몬·원피스 카드 자산과 취미비 회수 현황'],collection:['Collection','보유 카드와 수집 전략 관리'],transactions:['Transactions','매입·매도와 실제 현금흐름 관리'],grading:['Grading','PSA·BRG 출품 비용과 ROI 관리'],backup:['Backup','로컬 데이터 백업 및 복원']};
function go(v){$$('.view').forEach(x=>x.classList.remove('active'));$('#view-'+v).classList.add('active');$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#page-title').textContent=titles[v][0];$('#page-subtitle').textContent=titles[v][1];renderAll()}
function field(name,label,type='text',opts=[],full=false,value=''){let input;if(type==='select')input=`<select name="${name}">${opts.map(o=>`<option ${String(value)===o?'selected':''}>${o}</option>`).join('')}</select>`;else if(type==='textarea')input=`<textarea name="${name}">${value||''}</textarea>`;else input=`<input name="${name}" type="${type}" value="${value??''}" ${type==='number'?'min="0" step="1"':''}/>`;return `<div class="field ${full?'full':''}"><label>${label}</label>${input}</div>`}
function showModal(kind,data={}){currentModal={kind,data};let html='',title='';if(kind==='card'){title=data.id?'카드 수정':'카드 추가';html=field('name','카드명','text',[],false,data.name)+field('cardNo','카드번호','text',[],false,data.cardNo)+field('tcg','TCG','select',['Pokemon','One Piece','Other'],false,data.tcg||'One Piece')+field('language','언어','select',['JP','EN','KR','CN','Other'],false,data.language||'JP')+field('rarity','레어도 / 종류','text',[],false,data.rarity)+field('condition','상태','select',['S','A+','A','B','Other'],false,data.condition||'S')+field('form','현재 형태','select',['RAW','PSA','BRG','Other'],false,data.form||'RAW')+field('grade','등급','text',[],false,data.grade)+field('purchaseDate','매입일','date',[],false,data.purchaseDate)+field('purchasePrice','매입가','number',[],false,data.purchasePrice)+field('extraCost','부대비용','number',[],false,data.extraCost)+field('marketPrice','현재시세','number',[],false,data.marketPrice)+field('purpose','목적','select',['PC','Core Hold','Trade','Grading'],false,data.purpose||'PC')+field('strategy','전략','select',['보유','BRG','PSA','RAW매도','등급매도','관망'],false,data.strategy||'보유')+field('targetPrice','목표매도가','number',[],false,data.targetPrice)+field('image','카드 이미지','file',[],false,'')+field('memo','메모','textarea',[],true,data.memo)}
if(kind==='transaction'){title='거래 추가';html=field('cardId','카드','select',window.cardOptions||[],false,data.cardId)+field('type','구분','select',['매입','매도','그레이딩','기타'],false,data.type||'매입')+field('date','날짜','date',[],false,data.date||new Date().toISOString().slice(0,10))+field('amount','거래금액','number',[],false,data.amount)+field('fee','수수료','number',[],false,data.fee)+field('shipping','배송비','number',[],false,data.shipping)+field('otherCost','기타비용','number',[],false,data.otherCost)+field('memo','메모','textarea',[],true,data.memo)}
if(kind==='grading'){title='그레이딩 추가';html=field('cardId','카드','select',window.cardOptions||[],false,data.cardId)+field('company','업체','select',['PSA','BRG','Other'],false,data.company||'BRG')+field('submitDate','제출일','date',[],false,data.submitDate||new Date().toISOString().slice(0,10))+field('expectedGrade','예상등급','text',[],false,data.expectedGrade)+field('actualGrade','실제등급','text',[],false,data.actualGrade)+field('gradingCost','그레이딩비','number',[],false,data.gradingCost)+field('shippingCost','배송/기타','number',[],false,data.shippingCost)+field('gradedValue','등급시세','number',[],false,data.gradedValue)+field('status','상태','select',['출품예정','출품중','등급완료','판매완료','보유'],false,data.status||'출품예정')+field('memo','메모','textarea',[],true,data.memo)}
$('#modal-title').textContent=title;$('#modal-fields').innerHTML=html;$('#modal').showModal()}
function readFile(file){return new Promise((res,rej)=>{if(!file)return res(null);const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function saveModal(e){e.preventDefault();const fd=new FormData(e.target),o=Object.fromEntries(fd.entries()),{kind,data}=currentModal;if(kind==='card'){const img=await readFile(e.target.elements.image?.files?.[0]);['purchasePrice','extraCost','marketPrice','targetPrice'].forEach(k=>o[k]=Number(o[k]||0));o.id=data.id||uid();o.createdAt=data.createdAt||Date.now();o.image=img||data.image||'';await put('cards',o)}else if(kind==='transaction'){['amount','fee','shipping','otherCost'].forEach(k=>o[k]=Number(o[k]||0));o.id=data.id||uid();await put('transactions',o)}else{['gradingCost','shippingCost','gradedValue'].forEach(k=>o[k]=Number(o[k]||0));o.id=data.id||uid();await put('grading',o)}$('#modal').close();await renderAll()}
function cardHtml(c){const cost=+c.purchasePrice+(+c.extraCost||0),pl=+c.marketPrice-cost,cls=pl>=0?'positive':'negative';return `<article class="tcg-card"><div class="card-image">${c.image?`<img src="${c.image}" alt="">`:'NO IMAGE'}</div><div class="card-body"><div class="card-tags"><span class="tag">${c.tcg}</span><span class="tag">${c.language}</span><span class="tag">${c.form}${c.grade?' '+c.grade:''}</span><span class="tag">${c.purpose}</span></div><h3>${c.name||'이름 없음'}</h3><div class="card-no">${c.cardNo||'-'} · ${c.strategy||'-'}</div><div class="money-row"><span>매입 ${money(cost)}</span><strong>${money(c.marketPrice)}</strong></div><div class="money-row"><span>평가손익</span><strong class="${cls}">${pl>=0?'+':''}${money(pl)}</strong></div><div class="card-actions"><button data-edit-card="${c.id}">수정</button><button data-del-card="${c.id}" class="danger">삭제</button></div></div></article>`}
async function renderAll(){const cards=await all('cards'),tx=await all('transactions'),gr=await all('grading');window._cards=cards;window.cardOptions=cards.map(c=>c.name+' | '+(c.cardNo||c.id));const mapName=v=>{const c=cards.find(x=>(x.name+' | '+(x.cardNo||x.id))===v||x.id===v);return c?c.name+(c.cardNo?' · '+c.cardNo:''):v};const cost=cards.reduce((a,c)=>a+(+c.purchasePrice||0)+(+c.extraCost||0),0),value=cards.reduce((a,c)=>a+(+c.marketPrice||0),0),pl=value-cost,cash=tx.reduce((a,x)=>{const expenses=(+x.fee||0)+(+x.shipping||0)+(+x.otherCost||0);return a+(x.type==='매도'?(+x.amount-expenses):-(+x.amount+expenses))},0);$('#m-value').textContent=money(value);$('#m-cost').textContent=money(cost);$('#m-pl').textContent=(pl>=0?'+':'')+money(pl);$('#m-pl').className=pl>=0?'positive':'negative';$('#m-roi').textContent=(cost?pl/cost*100:0).toFixed(1)+'%';$('#m-cash').textContent=money(cash);breakdown('#tcg-breakdown',cards,'tcg');breakdown('#purpose-breakdown',cards,'purpose');$('#recent-cards').innerHTML=cards.sort((a,b)=>b.createdAt-a.createdAt).slice(0,4).map(cardHtml).join('')||'<div class="empty">아직 등록된 카드가 없습니다.</div>';renderCollection(cards);$('#transactions-body').innerHTML=tx.sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(x=>{const expenses=+x.fee+(+x.shipping||0)+(+x.otherCost||0),net=x.type==='매도'?+x.amount-expenses:-(+x.amount+expenses);return `<tr><td>${x.date||'-'}</td><td>${mapName(x.cardId)}</td><td>${x.type}</td><td>${money(x.amount)}</td><td>${money(expenses)}</td><td class="${net>=0?'positive':'negative'}">${money(net)}</td><td><button data-del-tx="${x.id}">삭제</button></td></tr>`}).join('')||'<tr><td colspan="7">거래 내역이 없습니다.</td></tr>';$('#grading-body').innerHTML=gr.map(x=>{const c=cards.find(c=>(c.name+' | '+(c.cardNo||c.id))===x.cardId),raw=c?(+c.purchasePrice+(+c.extraCost||0)):0,total=raw+(+x.gradingCost||0)+(+x.shippingCost||0),roi=total?(+x.gradedValue-total)/total*100:0;return `<tr><td>${mapName(x.cardId)}</td><td>${x.company}</td><td>${x.submitDate||'-'}</td><td>${x.expectedGrade||'-'}</td><td>${x.actualGrade||'-'}</td><td>${money(total)}</td><td>${money(x.gradedValue)}</td><td class="${roi>=0?'positive':'negative'}">${roi.toFixed(1)}%</td><td>${x.status}</td><td><button data-del-grade="${x.id}">삭제</button></td></tr>`}).join('')||'<tr><td colspan="10">그레이딩 내역이 없습니다.</td></tr>'}
function breakdown(sel,cards,key){const el=$(sel),counts={};cards.forEach(c=>counts[c[key]]=(counts[c[key]]||0)+1);const total=cards.length||1;el.innerHTML=Object.entries(counts).map(([k,v])=>`<div class="breakdown-row"><span>${k}</span><div class="bar"><i style="width:${v/total*100}%"></i></div><strong>${Math.round(v/total*100)}%</strong></div>`).join('')||'<span class="empty">데이터 없음</span>'}
function renderCollection(cards){const q=($('#card-search')?.value||'').toLowerCase(),tcg=$('#filter-tcg')?.value||'',purpose=$('#filter-purpose')?.value||'';const f=cards.filter(c=>(!q||(c.name+' '+c.cardNo).toLowerCase().includes(q))&&(!tcg||c.tcg===tcg)&&(!purpose||c.purpose===purpose));$('#collection-list').innerHTML=f.map(cardHtml).join('')||'<div class="empty">조건에 맞는 카드가 없습니다.</div>'}
async function exportJSON(){const data={version:1,exportedAt:new Date().toISOString(),cards:await all('cards'),transactions:await all('transactions'),grading:await all('grading')};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`ninnin-tcg-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function importJSON(file){const data=JSON.parse(await file.text());if(!Array.isArray(data.cards))throw Error('올바른 백업 파일이 아닙니다.');if(!confirm('현재 데이터를 백업 파일로 교체할까요?'))return;for(const n of ['cards','transactions','grading']){await clear(n);for(const x of (data[n]||[]))await put(n,x)}await renderAll();alert('복원이 완료되었습니다.')}
document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-go]');if(!b)return;if(b.dataset.view)go(b.dataset.view);if(b.dataset.go)go(b.dataset.go);if(b.id==='quick-add'||b.id==='add-card')showModal('card');if(b.id==='add-transaction')showModal('transaction');if(b.id==='add-grading')showModal('grading');if(b.id==='modal-close'||b.id==='modal-cancel')$('#modal').close();if(b.dataset.editCard)showModal('card',window._cards.find(c=>c.id===b.dataset.editCard));if(b.dataset.delCard&&confirm('이 카드를 삭제할까요?')){await del('cards',b.dataset.delCard);renderAll()}if(b.dataset.delTx&&confirm('이 거래를 삭제할까요?')){await del('transactions',b.dataset.delTx);renderAll()}if(b.dataset.delGrade&&confirm('이 기록을 삭제할까요?')){await del('grading',b.dataset.delGrade);renderAll()}if(b.id==='export-json')exportJSON();if(b.id==='reset-data'&&confirm('모든 데이터를 삭제합니다. 계속할까요?')){for(const n of ['cards','transactions','grading'])await clear(n);renderAll()}});
$('#modal-form').addEventListener('submit',saveModal);$('#card-search').addEventListener('input',()=>renderCollection(window._cards||[]));$('#filter-tcg').addEventListener('change',()=>renderCollection(window._cards||[]));$('#filter-purpose').addEventListener('change',()=>renderCollection(window._cards||[]));$('#import-json').addEventListener('change',e=>importJSON(e.target.files[0]).catch(err=>alert(err.message)));
(async()=>{db=await openDB();await renderAll()})();
